const goButton = document.querySelector('.goButton')
const backButton = document.querySelector('.backButton')
const michelleCard = document.querySelector('.michelleCard')
const shareCard = document.querySelector('.shareCard')
const scale = document.querySelector('.scale')
const mdBackButton = document.querySelector('.mdBackButton')

goButton.addEventListener('click', function () {
	michelleCard.classList.add('hidden', 'md:block')
	goButton.classList.add('hidden')
	scale.classList.add('h-[504px]')
	shareCard.classList.remove('hidden')
	scale.classList.remove('h-[512px]')
	mdBackButton.classList.remove('md:hidden')
})
backButton.addEventListener('click', function () {
	michelleCard.classList.remove('hidden')
	shareCard.classList.add('hidden')
	goButton.classList.remove('hidden')
	scale.classList.remove('h-[504px]')
	scale.classList.add('h-[512px]')
})
mdBackButton.addEventListener('click', function () {
	michelleCard.classList.remove('hidden','md:block')
	goButton.classList.remove('hidden')
	shareCard.classList.add('hidden')
	scale.classList.remove('h-[504px]')
	mdBackButton.classList.add('hidden','md:hidden')
})
